/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.personel;
import GUI_Packege.ogrenci.OgrenciKayit;
import StudentServiceClass.DbConnection;
import StudentServiceClass.SadeceSayilar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
/**
 *
 * @author blue
 */
public class PersonelKayit extends javax.swing.JInternalFrame {
DbConnection databs;
public Object ID;
SadeceSayilar sayi=new SadeceSayilar();
    /**
     * Creates new form Ogrenci_Kayit
     * @param databs
     */
    public PersonelKayit(DbConnection databs) {
    this.databs=databs;
        initComponents();
        setLocation(getWidth()/2,getHeight()/10);
            this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter(){
    @Override
    public void internalFrameClosing(InternalFrameEvent e){
        Reset(); 
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ADI = new javax.swing.JTextField();
        TLF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SOYADI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ADRES = new javax.swing.JTextArea();
        Kaydet = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboGorev = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Personel Kaydet");
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personel Kayıt"));
        jPanel1.setToolTipText("");

        jLabel8.setText("SOYADI:");

        jLabel1.setText("ADI:");

        jLabel2.setText("TELEFON:");

        jLabel5.setText("ADRES:");

        ADRES.setColumns(20);
        ADRES.setRows(5);
        jScrollPane1.setViewportView(ADRES);

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });

        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        jLabel3.setText("GÖREV:");

        jComboGorev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboGorevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Temizle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kaydet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboGorev, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                    .addComponent(TLF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SOYADI)
                    .addComponent(ADI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SOYADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGorev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temizle)
                    .addComponent(Kaydet))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
if(Kaydet.getText().equals("Güncelle")){
    update();
}
else{
    if(ADI.getText().equals(""))
        JOptionPane.showMessageDialog(rootPane,"Lütfen Personel Adını Giriniz.");
    else if(SOYADI.getText().equals(""))
        JOptionPane.showMessageDialog(rootPane,"Lütfen Personel Soyadını Giriniz.");
    else if(TLF.getText().equals(""))
        JOptionPane.showMessageDialog(rootPane,"Lütfen Personel Telefonu Giriniz.");
        else
    kaydet();
}
    }//GEN-LAST:event_KaydetActionPerformed

    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
    if(Temizle.getText().equals("Vazgeç")){
        Reset();
        this.hide();
    }else{
        Temizle();
      }
    }//GEN-LAST:event_TemizleActionPerformed

    private void jComboGorevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboGorevMouseClicked
     gorev_Cagir();
    }//GEN-LAST:event_jComboGorevMouseClicked

 void kaydet()
{
int id=SecilenGOREV();
String addRow = "INSERT INTO personel (GOREV_ID,ADI,SOYADI,TELEFON,ADRES,IPTAL"
        + ")"
        + "VALUES('"+id+"','"+ADI.getText()+"','"+SOYADI.getText()+"','"+TLF.getText()+"','"+ADRES.getText()+"',0"
        + ")";  
    try {
            databs.openDatabase();
            databs.sttmnt.execute(addRow);
            JOptionPane.showMessageDialog(null, "Personel Kaydı Yapıldı.");
            Temizle();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
            Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            databs.closeDatabase();
            }
}
    void update(){
        int id=SecilenGOREV();
 String UpDate="UPDATE personel SET "
                + "GOREV_ID='"+id+"'"
                + ",ADI='"+ADI.getText()+"'"
                + ",SOYADI='"+SOYADI.getText()+"'"
                + ",ADRES='"+ADRES.getText()+"'"
                + ",TELEFON='"+TLF.getText()+"'"
                + ",IPTAL=0 WHERE ID="+ID+"";
            try {
                databs.openDatabase();
                databs.sttmnt.execute(UpDate);
                JOptionPane.showMessageDialog(null, "Bilgiler Güncellendi.");
                Reset();
                this.hide();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
                Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
            }finally{databs.closeDatabase();}
}
private void Temizle(){
       ADI.setText("");SOYADI.setText("");TLF.setText("");ADRES.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ADI;
    public javax.swing.JTextArea ADRES;
    public javax.swing.JButton Kaydet;
    public javax.swing.JTextField SOYADI;
    public javax.swing.JTextField TLF;
    public javax.swing.JButton Temizle;
    public javax.swing.JComboBox jComboGorev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public Integer SecilenGOREV()
{
    int id = 0;
        String firTable = "SELECT ID FROM gorev WHERE GOREVI='"+jComboGorev.getSelectedItem()+"'";
    try {
        databs.openDatabase();
        databs.sttmnt.executeQuery(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                id = Integer.valueOf(rs.getString("ID"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();}
   return id;
}
 public void gorev_Cagir(){
        LinkedHashSet<String> arraylist=new LinkedHashSet<>(); 
        String firTable = "SELECT GOREVI FROM gorev";
    try {
        databs.openDatabase();
        databs.sttmnt.execute(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
             String ad= rs.getString("GOREVI");
             arraylist.add(ad);            
            }
            Iterator i=arraylist.iterator();
          jComboGorev.removeAllItems();
            while(i.hasNext()){
           jComboGorev.addItem((Object)i.next());
             } 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();
    }
} 
        private void Reset() {
           Kaydet.setText("Kaydet");
           Temizle.setText("Temizle");
           ADI.setText("");
           SOYADI.setText("");
           TLF.setText("");
           ADRES.setText(""); 
        }
}
