/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.ogrenci;

import StudentServiceClass.DbConnection;
import StudentServiceClass.OnInstallmentPlan;
import StudentServiceClass.ReinstalData;
import StudentServiceClass.SadeceSayilar;
import StudentServiceClass.jxDate;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Administrator
 */
public class OdemeBilgisiOlustur extends javax.swing.JInternalFrame{
SadeceSayilar sayicontrol=new SadeceSayilar();
OnInstallmentPlan taksitle= new OnInstallmentPlan();
ReinstalData delettable = new ReinstalData();
DbConnection databs;
jxDate dt=new jxDate();
public int ID;
    /**
     * Creates new form Odeme_Sekli
     * @param databs
     */
    public OdemeBilgisiOlustur(DbConnection databs) {
        this.databs=databs;
        initComponents();
        setLocation(getWidth()/2,getHeight()/10);
       tarihOto.setDate((dt.curentDate()));
       tarihKendin.setDate(dt.curentDate());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLable10 = new javax.swing.JLabel();
        ADI = new javax.swing.JLabel();
        SOYADI = new javax.swing.JLabel();
        VELI_ADI = new javax.swing.JLabel();
        VELI_TLF = new javax.swing.JLabel();
        tas_personel = new javax.swing.JLabel();
        okulu = new javax.swing.JLabel();
        sinifi = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taksitTablo = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        otoTaksitEkleButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        taksitSayisiOto = new javax.swing.JFormattedTextField();
        odemeSekliOto = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pesinOdenenOto = new javax.swing.JFormattedTextField();
        toplamTutarOto = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        tarihOto = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        temizleOto = new javax.swing.JButton();
        kaydetOto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tarihKendin = new org.jdesktop.swingx.JXDatePicker();
        toplamTutar1 = new javax.swing.JFormattedTextField();
        taksittutar = new javax.swing.JFormattedTextField();
        odemesekli = new javax.swing.JComboBox();
        ekleMnl = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        temizleMnl = new javax.swing.JButton();
        kaydetMnl = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Öğrenci Ödeme Şekli Oluşturma Paneli");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Örenci Bilgileri"));

        jLabel1.setText("ADI:");

        jLabel2.setText("SOYADI:");

        jLabel3.setText("VELİ ADI:");

        jLabel4.setText("SINIFI:");

        jLabel5.setText("VELİ TELEFONU:");

        jLabel6.setText("TAŞIYACAK PERSONEL:");

        jLabel7.setText("ADRES:");

        jLable10.setText("OKULU:");

        ADI.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        ADI.setText("                                        ");
        ADI.setToolTipText("");

        SOYADI.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        SOYADI.setText("                                        ");
        SOYADI.setToolTipText("");

        VELI_ADI.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        VELI_ADI.setText("                                        ");
        VELI_ADI.setToolTipText("");

        VELI_TLF.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        VELI_TLF.setText("                                        ");
        VELI_TLF.setToolTipText("");

        tas_personel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        tas_personel.setText("                                        ");
        tas_personel.setToolTipText("");

        okulu.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        okulu.setText("                                        ");
        okulu.setToolTipText("");

        sinifi.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        sinifi.setText("                                        ");
        sinifi.setToolTipText("");

        adress.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        adress.setText("                                        ");
        adress.setToolTipText("");
        adress.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SOYADI, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(VELI_TLF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VELI_ADI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLable10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okulu, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(sinifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tas_personel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ADI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(okulu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLable10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SOYADI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sinifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VELI_ADI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tas_personel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VELI_TLF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adress, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Taksitlendirme Bilgileri"));

        taksitTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TAKSİT NO", "TARİH", "TAKSİTLER", "ÖDEME ŞEKLİ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(taksitTablo);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        otoTaksitEkleButton.setText("Ekle");
        otoTaksitEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otoTaksitEkleButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("ÖDEME ŞEKLİ");

        taksitSayisiOto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        taksitSayisiOto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taksitSayisiOtoKeyReleased(evt);
            }
        });

        odemeSekliOto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAKİT", "K.KARTI" }));

        jLabel11.setText("TAKSİT SAYISI");

        jLabel9.setText("PEŞİN ÖDENEN");

        pesinOdenenOto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        pesinOdenenOto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesinOdenenOtoKeyReleased(evt);
            }
        });

        toplamTutarOto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        toplamTutarOto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toplamTutarOtoKeyReleased(evt);
            }
        });

        jLabel8.setText("TOPLAM TUTAR");

        jLabel12.setText("TARİH");

        temizleOto.setText("Temizle");
        temizleOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleOtoActionPerformed(evt);
            }
        });

        kaydetOto.setText("Kaydet");
        kaydetOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetOtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tarihOto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesinOdenenOto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toplamTutarOto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taksitSayisiOto)
                    .addComponent(odemeSekliOto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temizleOto, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(otoTaksitEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaydetOto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tarihOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otoTaksitEkleButton))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(toplamTutarOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesinOdenenOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(kaydetOto))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(taksitSayisiOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(odemeSekliOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temizleOto))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("OTOMATİK TİKSİTLENDİR", jPanel3);

        toplamTutar1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        toplamTutar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toplamTutar1KeyReleased(evt);
            }
        });

        taksittutar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        taksittutar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taksittutarKeyReleased(evt);
            }
        });

        odemesekli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAKİT", "K.KARTI" }));

        ekleMnl.setText("EKLE");
        ekleMnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleMnlActionPerformed(evt);
            }
        });

        jLabel13.setText("TOPLAM TUTAR");

        jLabel14.setText("TARİH");

        jLabel15.setText("TAKSİT TUTAR");

        jLabel16.setText("ÖDEME ŞEKLİ");

        temizleMnl.setText("Temizle");
        temizleMnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleMnlActionPerformed(evt);
            }
        });

        kaydetMnl.setText("Kaydet");
        kaydetMnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetMnlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tarihKendin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taksittutar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toplamTutar1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odemesekli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(temizleMnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ekleMnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kaydetMnl))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihKendin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekleMnl)
                    .addComponent(jLabel14))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toplamTutar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taksittutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kaydetMnl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odemesekli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(temizleMnl))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KENDİN OLUŞTUR", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ogrenciBilgi(int ID){
    this.ID=ID;
    databs.openDatabase();
String mySQL ="SELECT O.ID,\n" +
"    O.ADI,\n" +
"    O.SOYADI,\n" +
"    O.VELI_ADI,\n" +
"    O.VELI_GSM,\n" +
"    OK.OKUL_ADI,\n" +
"    O.SINIF,\n" +
"    CONCAT(P.ADI,' ',P.SOYADI) AS PERSONEL,\n" +
"    O.ADRES\n" +
"FROM \n" +
"    ogrenci O,\n" +
"    okul OK,\n" +
"    personel P,\n" +
"    arac A\n" +
"WHERE \n" +
"    O.OKUL_ID=OK.ID AND \n" +
"    O.ARAC_ID=A.ID AND A.PERSONEL_ID=P.ID AND O.IPTAL=0 AND O.ID="+this.ID+"";
    try {        
        databs.sttmnt.execute(mySQL);
        ResultSet rs = databs.sttmnt.getResultSet();
        while(rs!=null&&rs.next()){
        ADI.setText(rs.getString(2));
        SOYADI.setText(rs.getString(3));
        VELI_ADI.setText(rs.getString(4));
        VELI_TLF.setText(rs.getString(5));
        okulu.setText(rs.getString(6));
        sinifi.setText(rs.getString(7));
        tas_personel.setText(rs.getString(8));
        adress.setText(rs.getString(9));
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciHareket.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
databs.closeDatabase();}
    }
    
    private void ekleMnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleMnlActionPerformed
      DefaultTableModel model6 = (DefaultTableModel)taksitTablo.getModel();
      if(toplamTutar1.getValue()==null)
      {
      JOptionPane.showMessageDialog(pesinOdenenOto, "Lütfen Toplam Tutarı boş bırakmayınız.");
      }
     else if(taksittutar.getValue()==null)
      {
  model6.addRow(new Object[]{taksitle.taksitCounter(),dt.getMonth(tarihKendin),toplamTutar1.getValue(),odemesekli.getSelectedItem()});
    toplamTutar1.setValue(0);
    taksittutar.setValue(0);
      }
      else
      {
      double kalansonuc=taksitle.installmentonebyone(toplamTutar1.getValue(),taksittutar.getValue());
      if(kalansonuc>0)
      {
        if(taksitle.flag!=false)
        {
            toplamTutar1.setValue(kalansonuc);
        }else{ 
            toplamTutar1.setValue(0);
             }   
      model6.addRow(new Object[]{taksitle.taksitCounter(),dt.getMonth(tarihKendin),taksittutar.getValue(),odemesekli.getSelectedItem()});
      }
      else if(kalansonuc<0&&taksitle.flag!=false)
      {
       model6.addRow(new Object[]{taksitle.taksitCounter(),dt.getMonth(tarihKendin),toplamTutar1.getValue(),odemesekli.getSelectedItem()}); 
       taksitle.flag=false;
       toplamTutar1.setValue(0);
       taksitle.cnt=0;
      }
      }
    }//GEN-LAST:event_ekleMnlActionPerformed

    private void taksittutarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taksittutarKeyReleased
        sayicontrol.numberDoubleFloat(evt.getKeyChar(),taksittutar);// TODO add your handling code here:
    }//GEN-LAST:event_taksittutarKeyReleased

    private void toplamTutar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toplamTutar1KeyReleased
       sayicontrol.numberDoubleFloat(evt.getKeyChar(),toplamTutar1); // TODO add your handling code here:
    }//GEN-LAST:event_toplamTutar1KeyReleased

    private void toplamTutarOtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toplamTutarOtoKeyReleased
        sayicontrol.numberDoubleFloat(evt.getKeyChar(),toplamTutarOto);  // TODO add your handling code here:
    }//GEN-LAST:event_toplamTutarOtoKeyReleased

    private void pesinOdenenOtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesinOdenenOtoKeyReleased
        sayicontrol.numberDoubleFloat(evt.getKeyChar(),pesinOdenenOto);  // TODO add your handling code here:
    }//GEN-LAST:event_pesinOdenenOtoKeyReleased

    private void taksitSayisiOtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taksitSayisiOtoKeyReleased
        sayicontrol.numberDoubleFloat(evt.getKeyChar(),taksitSayisiOto);        // TODO add your handling code here:
    }//GEN-LAST:event_taksitSayisiOtoKeyReleased

    private void otoTaksitEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otoTaksitEkleButtonActionPerformed
        DefaultTableModel model6 = (DefaultTableModel)taksitTablo.getModel();
        if(tarihOto.getDate() == null)
        {
            JOptionPane.showMessageDialog(pesinOdenenOto,"Lütfen Tarih Giriniz.");
        }
        if(toplamTutarOto.getValue() == null)
        {
            JOptionPane.showMessageDialog(pesinOdenenOto,"Lütfen Toplam Tutarı Giriniz.");
        }
        if(pesinOdenenOto.getValue() == null||taksitSayisiOto.getValue() == null)
        {
            pesinOdenenOto.setValue(toplamTutarOto.getValue());
            taksitSayisiOto.setValue(0);
        }
        else
        {
            model6.addRow(new Object[]{"Peşin",dt.getMonth(tarihOto),pesinOdenenOto.getValue(),odemeSekliOto.getSelectedItem()});
            taksitle.installments(toplamTutarOto.getValue(),pesinOdenenOto.getValue(),taksitSayisiOto.getValue());
            
            double taksitpesin=taksitle.getTaksitpesin();
            double taksit=taksitle.getTaksit();
            do
           {
          if(taksitpesin>taksit)
          { 
           model6.addRow(new Object[]{taksitle.taksitCounter(),dt.getMonth(tarihOto),taksit,odemeSekliOto.getSelectedItem()});
          }
          else
          {
            model6.addRow(new Object[]{taksitle.taksitCounter(),dt.getMonth(tarihOto),taksitpesin,odemeSekliOto.getSelectedItem()});
          }
            taksitpesin-=taksit;
      }while(taksitpesin>0);
        }
        temizleOto();
    }//GEN-LAST:event_otoTaksitEkleButtonActionPerformed

    private void temizleMnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleMnlActionPerformed
      DefaultTableModel model6 = (DefaultTableModel)taksitTablo.getModel();
      delettable.reinstalData(model6);
        temizleMan();
    }//GEN-LAST:event_temizleMnlActionPerformed

    private void temizleOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleOtoActionPerformed
      DefaultTableModel model6 = (DefaultTableModel)taksitTablo.getModel();
      delettable.reinstalData(model6);
        temizleOto();
    }//GEN-LAST:event_temizleOtoActionPerformed

    private void kaydetOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetOtoActionPerformed
        Kaydet();
    }//GEN-LAST:event_kaydetOtoActionPerformed

    private void kaydetMnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetMnlActionPerformed
        Kaydet();
    }//GEN-LAST:event_kaydetMnlActionPerformed
public void Kaydet()
{
    int count=0;

    try {
        databs.openDatabase();
    for(int i=0;i<taksitTablo.getModel().getRowCount();i++){
String addRow = "INSERT INTO taksit "
        + "("
              + "OGRENCI_ID,"
                + "TAKSIT_NO,"
                + "TAKSIT_MIKTARI,"
                + "OLUSTURMA_TARIH,"
                + "ODEME_TARIHI,"
                + "ODEME_SEKLI,"
                + "ODEME_DURUM,"
                + "IPTAL"
        + ")"
        + "VALUES("
       + "'"+ID+"',"
        + "'"+taksitTablo.getModel().getValueAt(i,0)+"',"
        + "'"+taksitTablo.getModel().getValueAt(i,2)+"',"
        + "STR_TO_DATE('"+taksitTablo.getModel().getValueAt(0,1)+"','%d-%m-%Y'),"
        + "STR_TO_DATE('"+taksitTablo.getModel().getValueAt(i,1)+"','%d-%m-%Y'),"
        + "'"+taksitTablo.getModel().getValueAt(i,3)+"',"
        + "0,"
        + "0"
        + ")";
            databs.sttmnt.execute(addRow);
            count++;
    }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
            Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
    databs.closeDatabase();
    if(count==taksitTablo.getModel().getRowCount())
    JOptionPane.showMessageDialog(null, "Taksit Kaydı Yapıldı.");
    count=0;
    }
}
    
private void temizleOto(){
      tarihOto.setDate(null);
      toplamTutarOto.setValue(null);
      taksitSayisiOto.setValue(null);
      pesinOdenenOto.setValue(null);
      taksitle.cnt=0;
}
private void temizleMan(){
       taksitle.flag=true;
       taksitle.cnt=0;
       toplamTutar1.setValue(null);
       taksittutar.setValue(null);
       tarihKendin.setDate(null);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADI;
    private javax.swing.JLabel SOYADI;
    private javax.swing.JLabel VELI_ADI;
    private javax.swing.JLabel VELI_TLF;
    private javax.swing.JLabel adress;
    private javax.swing.JButton ekleMnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kaydetMnl;
    private javax.swing.JButton kaydetOto;
    private javax.swing.JComboBox odemeSekliOto;
    private javax.swing.JComboBox odemesekli;
    private javax.swing.JLabel okulu;
    private javax.swing.JButton otoTaksitEkleButton;
    private javax.swing.JFormattedTextField pesinOdenenOto;
    private javax.swing.JLabel sinifi;
    private javax.swing.JFormattedTextField taksitSayisiOto;
    private javax.swing.JTable taksitTablo;
    private javax.swing.JFormattedTextField taksittutar;
    private org.jdesktop.swingx.JXDatePicker tarihKendin;
    private org.jdesktop.swingx.JXDatePicker tarihOto;
    private javax.swing.JLabel tas_personel;
    private javax.swing.JButton temizleMnl;
    private javax.swing.JButton temizleOto;
    private javax.swing.JFormattedTextField toplamTutar1;
    private javax.swing.JFormattedTextField toplamTutarOto;
    // End of variables declaration//GEN-END:variables
}