/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.ogrenci;

import StudentServiceClass.DbConnection;
import StudentServiceClass.jxDate;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
/**
 *
 * @author zehirugur
 */
public class OgrenciKayit extends javax.swing.JInternalFrame {
DbConnection databs;
public Object ID;
    /**
     * Creates new form Ogrenci_Kayit
     * @param databs
     */
    public OgrenciKayit(DbConnection databs) {
        this.databs=databs;       
        initComponents();
        setLocation(getWidth()/4,getHeight()/10);
        jXDatePicker1.setDate(new jxDate().curentDate());
    this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter(){
    @Override
    public void internalFrameClosing(InternalFrameEvent e){
        Reset(); 
            }
        });
    ADI.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Kaydet = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        ADI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SOYADI = new javax.swing.JTextField();
        BABA_ADI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OKULU = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ADRES = new javax.swing.JTextArea();
        ogrenciTemizle = new javax.swing.JButton();
        SINIFI = new javax.swing.JComboBox();
        ogrenci_sayisi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        VELI_ADI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IS_ADRES = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        VELI_SOYADI = new javax.swing.JTextField();
        EV_TLF = new javax.swing.JFormattedTextField();
        GSM = new javax.swing.JFormattedTextField();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Öğrenci Kaydet");
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Öğrenci Bilgi Girişi", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setToolTipText("");

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        Kaydet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KaydetKeyReleased(evt);
            }
        });

        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });
        Temizle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TemizleKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Öğrenci Bilgileri"));

        jLabel12.setText("TARİH:");

        jLabel1.setText("ADI:");

        ADI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ADIKeyReleased(evt);
            }
        });

        jLabel8.setText("SOYADI:");

        SOYADI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SOYADIKeyReleased(evt);
            }
        });

        BABA_ADI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BABA_ADIKeyReleased(evt);
            }
        });

        jLabel2.setText("BABA ADI:");

        jLabel6.setText("OKULU:");

        OKULU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKULUMouseClicked(evt);
            }
        });
        OKULU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OKULUKeyReleased(evt);
            }
        });

        jLabel11.setText("SINIFI:");

        jLabel14.setText("ADRES:");

        ADRES.setColumns(20);
        ADRES.setLineWrap(true);
        ADRES.setRows(5);
        ADRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ADRESKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ADRES);

        ogrenciTemizle.setText("Temizle");
        ogrenciTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenciTemizleActionPerformed(evt);
            }
        });

        SINIFI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANAOKUL", "İLKÖĞRETİM 1", "İLKÖĞRETİM 2", "İLKÖĞRETİM 3", "İLKÖĞRETİM 4", "İLKÖĞRETİM 5", "İLKÖĞRETİM 6", "İLKÖĞRETİM 7", "İLKÖĞRETİM 8", "LİSE 1", "LİSE 2", "LİSE 3", "LİSE 4" }));
        SINIFI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SINIFIKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SINIFI, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OKULU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BABA_ADI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SOYADI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(ADI, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ogrenciTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogrenci_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ogrenciTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SOYADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BABA_ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKULU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SINIFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ogrenci_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Veli Bilgileri"));

        VELI_ADI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VELI_ADIKeyReleased(evt);
            }
        });

        jLabel5.setText("VELİ ADI:");

        IS_ADRES.setColumns(20);
        IS_ADRES.setRows(5);
        IS_ADRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IS_ADRESKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(IS_ADRES);

        jLabel10.setText("İŞ ADRES:");

        jLabel7.setText("EV TLF:");

        jLabel3.setText("GSM:");

        jLabel13.setText("VELİ SOYADI:");

        VELI_SOYADI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VELI_SOYADIKeyReleased(evt);
            }
        });

        try {
            EV_TLF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(5##) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            GSM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(5##) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VELI_SOYADI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VELI_ADI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EV_TLF)
                            .addComponent(GSM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VELI_ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VELI_SOYADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EV_TLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Temizle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Kaydet)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kaydet)
                    .addComponent(Temizle))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Öğrenci Kayıt Formu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        Kaydetbutton();
    }//GEN-LAST:event_KaydetActionPerformed

   private void Kaydetbutton(){
           if(Kaydet.getText().equals("Güncelle"))
        {
       update();
        }
        else{
            if(ADI.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane,"LÜTFEN ADINI YAZINIZ");
            else if(SOYADI.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane,"LÜTFEN SOYADINI YAZINIZ");
            else if(VELI_ADI.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane,"LÜTFEN VELİ ADINI YAZINIZ");
            else if(GSM.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane,"LÜTFEN VELİ TELEFONUNU YAZINIZ");
            else
            Kaydet();
            }
   }
    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
    if(Temizle.getText().equals("Vazgeç")){
        Reset();
        this.hide();
    }else{
        Reset();
    }
    }//GEN-LAST:event_TemizleActionPerformed

    private void OKULUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKULUMouseClicked
    Okul_Cagir();
    }//GEN-LAST:event_OKULUMouseClicked

    private void ogrenciTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenciTemizleActionPerformed
        ogrenciTemizle();
    }//GEN-LAST:event_ogrenciTemizleActionPerformed

    private void ADIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADIKeyReleased
        if(evt.getKeyCode()==10)
            SOYADI.requestFocus();
    }//GEN-LAST:event_ADIKeyReleased

    private void SOYADIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SOYADIKeyReleased
         if(evt.getKeyCode()==10)
            BABA_ADI.requestFocus();  // TODO add your handling code here:
    }//GEN-LAST:event_SOYADIKeyReleased

    private void BABA_ADIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BABA_ADIKeyReleased
         if(evt.getKeyCode()==10)
            OKULU.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_BABA_ADIKeyReleased

    private void OKULUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OKULUKeyReleased
          if(evt.getKeyCode()==10)
            SINIFI.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_OKULUKeyReleased

    private void SINIFIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SINIFIKeyReleased
         if(evt.getKeyCode()==10)
            ADRES.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_SINIFIKeyReleased

    private void ADRESKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADRESKeyReleased
            if(evt.getKeyCode()==10)
            VELI_ADI.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_ADRESKeyReleased

    private void VELI_ADIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VELI_ADIKeyReleased
            if(evt.getKeyCode()==10)
            VELI_SOYADI.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_VELI_ADIKeyReleased

    private void VELI_SOYADIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VELI_SOYADIKeyReleased
                  if(evt.getKeyCode()==10)
            EV_TLF.requestFocus();  // TODO add your handling code here:
    }//GEN-LAST:event_VELI_SOYADIKeyReleased

    private void IS_ADRESKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IS_ADRESKeyReleased
            if(evt.getKeyCode()==10)
           Kaydet.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_IS_ADRESKeyReleased

    private void KaydetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KaydetKeyReleased
        if(evt.getKeyCode()==10){
        Kaydetbutton();
        Temizle.requestFocus();}// TODO add your handling code here:
    }//GEN-LAST:event_KaydetKeyReleased

    private void TemizleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TemizleKeyReleased
    if(evt.getKeyCode()==10){
           Reset();
        ADI.requestFocus();} // TODO add your handling code here:
    }//GEN-LAST:event_TemizleKeyReleased
public void Okul_Cagir(){
         LinkedHashSet<String> arraylist=new LinkedHashSet<>();
         String firTable = "SELECT OKUL_ADI FROM okul WHERE IPTAL = 0";
    try {
        databs.openDatabase();
        databs.sttmnt.executeQuery(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
             arraylist.add(rs.getString("OKUL_ADI"));            
            }
            Iterator i=arraylist.iterator();
          OKULU.removeAllItems();
            while(i.hasNext()){
           OKULU.addItem((Object)i.next());
             } 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();}
}
Integer SecilenOKUL()
{
    int id = 0;
        String firTable = "SELECT ID FROM okul WHERE OKUL_ADI='"+OKULU.getSelectedItem()+"' AND IPTAL = 0";
    try {
        databs.openDatabase();
        databs.sttmnt.executeQuery(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                id = Integer.valueOf(rs.getString("ID"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();}
   return id;
}
void update(){
        int OK_id=SecilenOKUL();         
 String UpDate="UPDATE ogrenci SET "
        + "KAYIT_TARIH=STR_TO_DATE('"+new jxDate().getDate(jXDatePicker1)+"','%d-%m-%Y')"
        + ",ADI='"+ADI.getText()+"'"
        + ",SOYADI='"+SOYADI.getText()+"'"
        + ",BABA_ADI='"+BABA_ADI.getText()+"'"
        + ",OKUL_ID='"+OK_id+"'"
        + ",SINIF='"+SINIFI.getSelectedItem()+"'"
        + ",ADRES='"+ADRES.getText()+"'"
        + ",VELI_ADI='"+VELI_ADI.getText()+"'"        
        + ",VELI_SOYADI='"+VELI_SOYADI.getText()+"'"
        + ",VELI_GSM='"+GSM.getText()+"'"
        + ",VELI_EV_TLF='"+EV_TLF.getText()+"'"
        + ",IS_ADRES='"+IS_ADRES.getText()+"'"
        + ",IPTAL=0 WHERE ID="+ID+"";
            try {
                databs.openDatabase();
                databs.sttmnt.executeUpdate(UpDate);
                JOptionPane.showMessageDialog(null, "Bilgiler Güncellendi.");
                Reset();
                this.hide();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
                Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
            databs.closeDatabase();
            }
}
public void Kaydet()
{
   int OK_id=SecilenOKUL();   
String addRow = "INSERT INTO ogrenci ("
        + "KAYIT_TARIH"
        + ",ADI"
        + ",SOYADI"
        + ",BABA_ADI"
        + ",OKUL_ID"
        + ",SINIF"
        + ",ADRES"
        + ",VELI_ADI"        
        + ",VELI_SOYADI"
        + ",VELI_GSM"
        + ",VELI_EV_TLF"
        + ",IS_ADRES"
        + ",IPTAL"
        + ")"
        + "VALUES("
        + " STR_TO_DATE('"+new jxDate().getDate(jXDatePicker1)+"','%d-%m-%Y')"
        + ",'"+ADI.getText()+"'"
        + ",'"+SOYADI.getText()+"'"
        + ",'"+BABA_ADI.getText()+"'"
        + ",'"+OK_id+"'"
        + ",'"+SINIFI.getSelectedItem()+"'" 
        + ",'"+ADRES.getText()+"'"      
        + ",'"+VELI_ADI.getText()+"'"
        + ",'"+VELI_SOYADI.getText()+"'"
        + ",'"+GSM.getText()+"'"
        + ",'"+EV_TLF.getText()+"'"
        + ",'"+IS_ADRES.getText()+"'"
        + ",0" 
        + ")";  
        try {       
                databs.openDatabase();
                databs.sttmnt.executeUpdate(addRow);
                JOptionPane.showMessageDialog(null, "Öğrenci Kaydı Yapıldı.");
                ogrenciTemizle();
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
                Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                databs.closeDatabase();
                }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ADI;
    public javax.swing.JTextArea ADRES;
    public javax.swing.JTextField BABA_ADI;
    private javax.swing.JFormattedTextField EV_TLF;
    private javax.swing.JFormattedTextField GSM;
    public javax.swing.JTextArea IS_ADRES;
    public javax.swing.JButton Kaydet;
    public javax.swing.JComboBox OKULU;
    public javax.swing.JComboBox SINIFI;
    public javax.swing.JTextField SOYADI;
    public javax.swing.JButton Temizle;
    public javax.swing.JTextField VELI_ADI;
    public javax.swing.JTextField VELI_SOYADI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    public javax.swing.JButton ogrenciTemizle;
    private javax.swing.JLabel ogrenci_sayisi;
    // End of variables declaration//GEN-END:variables

        private void ogrenciTemizle() {
                ADI.setText("");
                SOYADI.setText("");
                BABA_ADI.setText("");
                ADRES.setText("");
                SINIFI.setSelectedIndex(0);
                OKULU.setEnabled(true);
        }
        private void veliTemizle() {
                VELI_ADI.setText("");
                VELI_SOYADI.setText("");
                GSM.setText("");
                EV_TLF.setText("");
                IS_ADRES.setText("");
        }
        private void Reset() {
                Kaydet.setText("Kaydet");
                Temizle.setText("Temizle");
                ADI.setText("");
                SOYADI.setText("");
                BABA_ADI.setText("");
                ADRES.setText("");
                SINIFI.setSelectedIndex(0);             
                VELI_ADI.setText("");
                VELI_SOYADI.setText("");
                GSM.setText("");
                EV_TLF.setText("");
                IS_ADRES.setText(""); 
                OKULU.setEnabled(true);
            }

    public void ogrenciGuncelle(int ID){
    this.ID=ID;
String mySQL ="SELECT " +
"    O.KAYIT_TARIH,\n" +        
//"  DATE_FORMAT(O.KAYIT_TARIH,'%d-%m-%Y'),\n" +
"    O.ADI,\n" +
"    O.SOYADI,\n" +
"    O.BABA_ADI,\n" +
"    OK.OKUL_ADI,\n" +
"    O.SINIF,\n" +
"    O.ADRES,\n" +
"    O.VELI_ADI,\n" +
"    O.VELI_SOYADI,\n" +
"    O.VELI_EV_TLF,\n" +
"    O.VELI_GSM,\n" +
"    O.IS_ADRES,\n" +
"    O.ARAC_ID\n" +
"FROM \n" +
"    ogrenci O,\n" +
"    okul OK \n" +
"WHERE \n" +
"    O.OKUL_ID=OK.ID AND \n" +
"     O.ID="+this.ID+"";
    try {      
        databs.openDatabase();
        databs.sttmnt.execute(mySQL);
        ResultSet rs = databs.sttmnt.getResultSet();
        while(rs!=null&&rs.next()){
        jXDatePicker1.setDate(rs.getDate(1));
        ADI.setText(rs.getString(2));
        SOYADI.setText(rs.getString(3));
        BABA_ADI.setText(rs.getString(4));
        OKULU.setSelectedItem((Object)rs.getString(5));
        SINIFI.setSelectedItem((Object)rs.getString(6));
        ADRES.setText(rs.getString(7));
        VELI_ADI.setText(rs.getString(8));
        VELI_SOYADI.setText(rs.getString(9));
        EV_TLF.setText(rs.getString(10));
        GSM.setText(rs.getString(11));
        IS_ADRES.setText(rs.getString(12));
        if("0".equals(rs.getString(13)))
        {
        OKULU.setEnabled(true);
        }
        else{OKULU.setEnabled(false);}
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciHareket.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
databs.closeDatabase();}
    }
}
