/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.okul;

import GUI_Packege.ogrenci.OgrenciKayit;
import StudentServiceClass.DbConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
/**
 *
 * @author blue
 */
public class OkulKayit extends javax.swing.JInternalFrame {
DbConnection databs;
public Object ID;
    /**
     * Creates new form Ogrenci_Kayit
     * @param databs
     */
    public OkulKayit(DbConnection databs) {
      this.databs=databs;
      initComponents();
      setLocation(getWidth()/2,getHeight()/10);
      this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter(){
      @Override
      public void internalFrameClosing(InternalFrameEvent e){
      Reset(); 
      }}); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ADI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ADRES = new javax.swing.JTextArea();
        Kaydet = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        AD_SOYAD_YET = new javax.swing.JTextField();
        TELEFON_YET = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Okul Kaydet");
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Okul Kaydet"));
        jPanel1.setToolTipText("");

        jLabel1.setText("OKUL ADI:");

        jLabel2.setText("ADRES:");

        ADRES.setColumns(20);
        ADRES.setRows(5);
        jScrollPane1.setViewportView(ADRES);

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });

        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        jLabel3.setText("YETKİLİ ADI SOYADI:");

        jLabel4.setText("TELEFON NO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(AD_SOYAD_YET)
                            .addComponent(TELEFON_YET))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ADI, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Temizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kaydet)
                    .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AD_SOYAD_YET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Temizle))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TELEFON_YET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
    if(Temizle.getText().equals("Vazgeç")){
    Reset();
    this.hide();
    }else{
     Temizle();
    }
    }//GEN-LAST:event_TemizleActionPerformed

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
if(Kaydet.getText().equals("Güncelle")){
Update();
}else{        
        if(ADI.getText().equals(""))
    JOptionPane.showMessageDialog(rootPane, "Okul Adını Giriniz.");
        else
    Kaydet();
}
    }//GEN-LAST:event_KaydetActionPerformed
void Kaydet(){        
    databs.openDatabase();
        String addRow = "INSERT INTO okul (OKUL_ADI,AD_SOYAD,TELEFON,ADRES,IPTAL"
        + ")"
        + "VALUES('"+ADI.getText()+"','"+AD_SOYAD_YET.getText()+"','"+TELEFON_YET.getText()+"','"+ADRES.getText()+"',0"
        + ")";
        try {
            databs.sttmnt.execute(addRow);
            JOptionPane.showMessageDialog(null, "Okul Kaydı Yapıldı.");
            Temizle();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
            Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        databs.closeDatabase();}
}
void Update(){
 String UpDate="UPDATE okul SET "
                + "OKUL_ADI='"+ADI.getText()+"'"
                + ",AD_SOYAD='"+AD_SOYAD_YET.getText()+"'"
                + ",TELEFON='"+TELEFON_YET.getText()+"'"
                + ",ADRES='"+ADRES.getText()+"'"
                + ",IPTAL=0 WHERE ID="+ID+"";
            try {
                databs.openDatabase();
                databs.sttmnt.execute(UpDate);
                JOptionPane.showMessageDialog(null, "Bilgiler Güncellendi.");
                Reset();
                this.hide();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
                Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
            }finally{databs.closeDatabase();}
}
private void Temizle() {
ADI.setText("");AD_SOYAD_YET.setText("");TELEFON_YET.setText(""); ADRES.setText(""); //To change body of generated methods, choose Tools | Templates.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ADI;
    public javax.swing.JTextArea ADRES;
    public javax.swing.JTextField AD_SOYAD_YET;
    public javax.swing.JButton Kaydet;
    public javax.swing.JTextField TELEFON_YET;
    public javax.swing.JButton Temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Reset(){
        Kaydet.setText("Kaydet");
        Temizle.setText("Temizle");
        ADI.setText("");
        AD_SOYAD_YET.setText("");
        TELEFON_YET.setText(""); 
        ADRES.setText("");
    }
}
