/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.arac;

import GUI_Packege.ogrenci.OgrenciKayit;
import StudentServiceClass.DbConnection;
import StudentServiceClass.SadeceSayilar;
import StudentServiceClass.jxDate;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
/**
 *
 * @author Administrator
 */
public class AracKayit extends javax.swing.JInternalFrame {
DbConnection databs;
public Object ID;
SadeceSayilar sayi=new SadeceSayilar();
jxDate dat=new jxDate();
    /**
     * Creates new form Ogrenci_Kayit
     * @param databs
     */
    public AracKayit(DbConnection databs) {
       this.databs=databs; 
        initComponents();
        setLocation(getWidth()/2,getHeight()/10);
        AracDatePicker.setDate(dat.curentDate());
      this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter(){
      @Override
      public void internalFrameClosing(InternalFrameEvent e){
      Reset(); 
      }});
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PLAKA = new javax.swing.JTextField();
        ARACTIPI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MODEL = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        PERSONEL = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        KOLTUK_SAYI = new javax.swing.JTextField();
        AracDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Araç Kaydet");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Araç Kaydet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setToolTipText(""); // NOI18N

        jLabel8.setText("MODEL:");

        jLabel1.setText("PLAKA:");

        jLabel2.setText("ARAÇ TİPİ:");

        PLAKA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PLAKAKeyReleased(evt);
            }
        });

        jLabel4.setText("PERSONEL:");

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });

        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        PERSONEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PERSONELMouseClicked(evt);
            }
        });

        jLabel3.setText("KOLTUK SAYISI:");

        jLabel5.setText("BASLAMA TARİHİ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Temizle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Kaydet))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AracDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(PERSONEL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(52, 52, 52)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PLAKA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ARACTIPI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addComponent(MODEL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(KOLTUK_SAYI, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AracDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PERSONEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PLAKA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KOLTUK_SAYI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MODEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ARACTIPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kaydet)
                    .addComponent(Temizle))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
if(Kaydet.getText().equals("Güncelle")){
        Update();
}else{        
       if(PLAKA.getText().equals(""))
    JOptionPane.showMessageDialog(rootPane, "Arac Plakasını Giriniz.");
       if(MODEL.getText().equals(""))
    JOptionPane.showMessageDialog(rootPane, "Arac Modelini Giriniz.");
       if(ARACTIPI.getText().equals(""))
    JOptionPane.showMessageDialog(rootPane, "Arac Tipini Giriniz.");
       if(KOLTUK_SAYI.getText().equals(""))
    JOptionPane.showMessageDialog(rootPane, "Koltuk Sayısını Giriniz.");
       else{
     if(!Duplicat(PLAKA.getText())){Kaydet();}
       }
       plakaMethodSifirla();
    }
    }//GEN-LAST:event_KaydetActionPerformed
void Update(){
   int id=SecilenPers();
 String UpDate="UPDATE arac SET "
                + "PLAKA='"+PLAKA.getText()+"'"
                + ",MODEL='"+MODEL.getText()+"'"
                + ",PERSONEL_ID='"+id+"'"
                + ",ARAC_TIP='"+ARACTIPI.getText()+"'"
                + ",KOLTUK_SAYISI='"+KOLTUK_SAYI.getText()+"'"
                + ",IPTAL=0 WHERE ID="+ID+"";
            try {
                databs.openDatabase();
                databs.sttmnt.execute(UpDate);
                JOptionPane.showMessageDialog(null, "Bilgiler Güncellendi.");
                Reset();
                this.hide();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
                Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
            }finally{databs.closeDatabase();}
}
   void Kaydet(){
   int id=SecilenPers();
    String addRow = "INSERT INTO arac (BASLA_TARIH,PLAKA,MODEL,PERSONEL_ID,ARAC_TIP,KOLTUK_SAYISI,IPTAL"
        + ")"
        + "VALUES(STR_TO_DATE('"+dat.getDate(AracDatePicker)+"','%d-%m-%Y'),'"+PLAKA.getText()+"','"+MODEL.getText()+"','"+id+"'"
        + ",'"+ARACTIPI.getText()+"','"+KOLTUK_SAYI.getText()+"',0"
        + ")";  
try {
            databs.openDatabase();
            databs.sttmnt.execute(addRow);
            JOptionPane.showMessageDialog(null, "Araç Kaydedildi.");
            Reset();
            plakaMethodSifirla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
            Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
        }finally{     
                databs.closeDatabase();
                }
}
    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
    if(Temizle.getText().equals("Vazgeç")){
        Reset();
    this.hide();
    }else{
     Temizle();
    }
    plakaMethodSifirla();
    }//GEN-LAST:event_TemizleActionPerformed
void Temizle()
{
PLAKA.setText("");
MODEL.setText("");
ARACTIPI.setText("");
KOLTUK_SAYI.setText("");
}
    private void PERSONELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PERSONELMouseClicked
        Personel_Cagir();
    }//GEN-LAST:event_PERSONELMouseClicked

    private void PLAKAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PLAKAKeyReleased
        sayi.plaka(evt.getKeyChar(), PLAKA);     // TODO add your handling code here:
    }//GEN-LAST:event_PLAKAKeyReleased
Integer SecilenPers()
{
    int id = 0;
String ad_soyad = String.valueOf(PERSONEL.getSelectedItem());
String[] parts = ad_soyad.split(" ");
String part1 = parts[0];
String part2 = parts[1];
        String firTable = "SELECT ID FROM personel WHERE ADI='"+part1+"' AND SOYADI='"+part2+"' AND IPTAL = 0";
    try {
        databs.openDatabase();
        databs.sttmnt.execute(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                id = Integer.valueOf(rs.getString("ID"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();}
   return id;
}
public void Personel_Cagir(){
          LinkedHashSet<String> arraylist=new LinkedHashSet<>(); 
            String firTable = "SELECT ADI,SOYADI FROM personel WHERE IPTAL = 0";
    try {
        databs.openDatabase();
        databs.sttmnt.execute(firTable);
         ResultSet rs = databs.sttmnt.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                String ad= rs.getString("ADI");
                String soyad= rs.getString("SOYADI");
             arraylist.add(ad+" "+soyad);            
            }
            Iterator i=arraylist.iterator();
          PERSONEL.removeAllItems();
            while(i.hasNext()){
           PERSONEL.addItem((Object)i.next());
             } 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciKayit.class.getName()).log(Level.SEVERE, null, ex);
    }finally{
    databs.closeDatabase();
    }
}

public boolean Duplicat(String plaka)
{
    String sql="SELECT PLAKA "
            + "FROM arac "
            + "WHERE PLAKA='"+plaka+"' "
            + "GROUP BY PLAKA "
            + "HAVING COUNT(*) > 0";
        try {
        databs.openDatabase();
        databs.sttmnt.executeQuery(sql);
        ResultSet rs=databs.sttmnt.getResultSet();
        while((rs!=null) && (rs.next()))
          {
           JOptionPane.showMessageDialog(rootPane, rs.getString("PLAKA")+" Nolu Plaka Sistemde Kayıtlıdır.");
           return true;
          }            
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(),"Database error",JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(AracKayit.class.getName()).log(Level.SEVERE,null,e);
    }finally{
        databs.closeDatabase();
        }
     return false;       
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ARACTIPI;
    public org.jdesktop.swingx.JXDatePicker AracDatePicker;
    public javax.swing.JTextField KOLTUK_SAYI;
    public javax.swing.JButton Kaydet;
    public javax.swing.JTextField MODEL;
    public javax.swing.JComboBox PERSONEL;
    public javax.swing.JTextField PLAKA;
    public javax.swing.JButton Temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void plakaMethodSifirla() {
       sayi.alfa=false;
       sayi.sayi=false;
       sayi.str="";
    }
        private void buttonReset() {
    Kaydet.setText("Kaydet");
    Temizle.setText("Temizle");
        }
    private void Reset() {
    Kaydet.setText("Kaydet");
    Temizle.setText("Temizle");
    PLAKA.setText("");
    MODEL.setText("");
    ARACTIPI.setText("");
    KOLTUK_SAYI.setText("");
    }
}
