/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_Packege.kulanici;

import StudentServiceClass.AESencrp;
import StudentServiceClass.DbConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Blue
 */
public class KulaniciEkle extends javax.swing.JPanel {
    DbConnection databs=new DbConnection();
   private String lgn;
   private String sfr;
   private String adsyd;
    /**
     * Creates new form NewJPanel1
     */
    public KulaniciEkle() 
        {
        initComponents();
        kayitgir.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kayitgir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        adisoyadi = new javax.swing.JTextField();
        loginadi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        sifretekrar = new javax.swing.JPasswordField();
        sifresles = new javax.swing.JLabel();

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kulan�c� Ekle", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel17.setText("Ad� Soyad�:");

        jLabel18.setText("�ifresi:");

        kayitgir.setText("Kayd� Gir");
        kayitgir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitgirActionPerformed(evt);
            }
        });

        jButton5.setText("Formu Temizle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel20.setText("�ifresi Tekrar:");

        jLabel21.setText("Kulan�c� Ad�:");

        sifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sifreKeyReleased(evt);
            }
        });

        sifretekrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sifretekrarKeyReleased(evt);
            }
        });

        sifresles.setForeground(new java.awt.Color(204, 0, 0));
        sifresles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sifresles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adisoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(loginadi)
                    .addComponent(sifre)
                    .addComponent(sifretekrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kayitgir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(adisoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayitgir))
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(loginadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sifretekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sifresles, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kayitgirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitgirActionPerformed
        if(adisoyadi.getText().equals("") & loginadi.getText().equals("")){
            JOptionPane.showMessageDialog(kayitgir, "L�tfen Ad� Soyad�: ve Kulan�c� Ad�: alanlar�n� eksiksiz doldurun. ");
        }else{
        try {
            adsyd=AESencrp.encrypt(adisoyadi.getText());
            lgn=AESencrp.encrypt(loginadi.getText());
            sfr=AESencrp.encrypt(sifre.getText());
        }catch (Exception ex) {
            Logger.getLogger(KulaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    try {    
        databs.openDatabase();
   String addRow = "INSERT INTO menu (name_surname,login_name,password) VALUES('"+adsyd+"','"+lgn+"','"+sfr+"')"; 
       try {
          databs.sttmnt.execute(addRow);
          adisoyadi.setText("");
          loginadi.setText("");
          sifre.setText("");
          sifretekrar.setText("");
            } 
         catch (SQLException ex)
                {
            Logger.getLogger(DbConnection.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
        Logger.getLogger(KulaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
    }
     databs.closeDatabase();
    }//GEN-LAST:event_kayitgirActionPerformed
    }
    
    private void sifretekrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifretekrarKeyReleased
if(sifre.getText() == null ? sifretekrar.getText() == null : sifre.getText().equals(sifretekrar.getText())){
    sifresles.setText(null);
    kayitgir.setEnabled(true);
}else{
kayitgir.setEnabled(false);
sifresles.setText("�ifreniz E�le�medi");
}

// TODO add your handling code here:
    }//GEN-LAST:event_sifretekrarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
adisoyadi.setText("");
loginadi.setText("");
sifre.setText("");
sifretekrar.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sifreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifreKeyReleased
if(sifre.getText() == null ? sifretekrar.getText() == null : sifre.getText().equals(sifretekrar.getText())|"".equals(sifretekrar.getText()))
    {
    sifresles.setText(null);
    //kayitgir.setEnabled(true);
    }else
      {
      kayitgir.setEnabled(false);
      sifresles.setText("�ifreniz E�le�medi");
      }  // TODO add your handling code here:
    }//GEN-LAST:event_sifreKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adisoyadi;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton kayitgir;
    private javax.swing.JTextField loginadi;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JLabel sifresles;
    private javax.swing.JPasswordField sifretekrar;
    // End of variables declaration//GEN-END:variables
}
