/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_Packege.kulanici;

/**
 *
 * @author Blue
 */
public class KulaniciYetkileri extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel4
     */
    public KulaniciYetkileri() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        udspanel58 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel264 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        iskontoyapabilsin = new javax.swing.JCheckBox();
        musterifirmakayitsil = new javax.swing.JCheckBox();
        musterifirmabilgileriduzen = new javax.swing.JCheckBox();
        firmatakvimlerineislem = new javax.swing.JCheckBox();
        musteritakvimlerineislem = new javax.swing.JCheckBox();
        satisfiyatdegistirme = new javax.swing.JCheckBox();
        hareketduzenleyebilsin = new javax.swing.JCheckBox();
        hareketiptaletme = new javax.swing.JCheckBox();
        barkodyaz = new javax.swing.JCheckBox();
        smsgonder = new javax.swing.JCheckBox();
        genelayar = new javax.swing.JCheckBox();
        satisfisiayar = new javax.swing.JCheckBox();
        irsaliyefaturaayar = new javax.swing.JCheckBox();
        irsaliyeayar = new javax.swing.JCheckBox();
        dovizkurlari = new javax.swing.JCheckBox();
        sifredegistir = new javax.swing.JCheckBox();
        faturaayar = new javax.swing.JCheckBox();
        yapilacakirsaliyefaturalist = new javax.swing.JCheckBox();
        irsaliyefaturayaz = new javax.swing.JCheckBox();
        personelodeme = new javax.swing.JCheckBox();
        personeltanimla = new javax.swing.JCheckBox();
        bankahesaphareket = new javax.swing.JCheckBox();
        bankahesaptanimla = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        udspanel58.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Yetkileri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jComboBox1.setEditable(true);

        jLabel264.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel264.setText("Kullanıcı Adı:");

        jButton3.setText("Güncelle");

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        iskontoyapabilsin.setText("İskonto Yapabilsin");

        musterifirmakayitsil.setText("Müşteri / Firma Kayıtlarını Silebilsin");

        musterifirmabilgileriduzen.setText("Müşteri / Firma Bilgilerini Düzenleyebilsin");

        firmatakvimlerineislem.setText("Firma Takvimlerine İşlem Yapabilsin");

        musteritakvimlerineislem.setText("Müşteri Takvimlerine İşlem Yapabilsin");

        satisfiyatdegistirme.setText("Satış Fiyatı Değiştire Bilsin");

        hareketduzenleyebilsin.setText("Hareketleri Düzenleyebilsin");

        hareketiptaletme.setText("Hareketleri İptal Edebilsin");

        barkodyaz.setText("Barkod Yazdır");

        smsgonder.setText("Sms Gönder");

        genelayar.setText("Genel Ayarlar");

        satisfisiayar.setText("Satiş Fişi Ayarları");

        irsaliyefaturaayar.setText("İrsaliye Fatura Ayarları");

        irsaliyeayar.setText("İrsaliye Ayarları");

        dovizkurlari.setText("Döviz Kurları");

        sifredegistir.setText("Şifre Değiştirme");

        faturaayar.setText("Fatura Ayarları");

        yapilacakirsaliyefaturalist.setText("Yapılacak İrsaliye/Fatura Listesi");

        irsaliyefaturayaz.setText("İrsaliye / Fatura Yazdır");

        personelodeme.setText("Personel Ödeme İşlemleri");

        personeltanimla.setText("Personel Tanımlama İşlemleri");

        bankahesaphareket.setText("Banka Hesap Hareket İşlemleri");

        bankahesaptanimla.setText("Banka Hesap Tanımlama İşlemleri");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iskontoyapabilsin)
                    .addComponent(musterifirmakayitsil)
                    .addComponent(musterifirmabilgileriduzen)
                    .addComponent(firmatakvimlerineislem)
                    .addComponent(musteritakvimlerineislem)
                    .addComponent(satisfiyatdegistirme)
                    .addComponent(hareketduzenleyebilsin)
                    .addComponent(hareketiptaletme)
                    .addComponent(barkodyaz)
                    .addComponent(smsgonder)
                    .addComponent(genelayar)
                    .addComponent(satisfisiayar)
                    .addComponent(irsaliyefaturaayar)
                    .addComponent(irsaliyeayar)
                    .addComponent(dovizkurlari)
                    .addComponent(sifredegistir)
                    .addComponent(faturaayar)
                    .addComponent(yapilacakirsaliyefaturalist)
                    .addComponent(irsaliyefaturayaz)
                    .addComponent(personelodeme)
                    .addComponent(personeltanimla)
                    .addComponent(bankahesaphareket)
                    .addComponent(bankahesaptanimla))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(bankahesaptanimla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bankahesaphareket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personeltanimla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personelodeme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(irsaliyefaturayaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yapilacakirsaliyefaturalist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dovizkurlari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sifredegistir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(faturaayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(irsaliyeayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(irsaliyefaturaayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(satisfisiayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genelayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smsgonder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barkodyaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hareketiptaletme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hareketduzenleyebilsin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(satisfiyatdegistirme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musteritakvimlerineislem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firmatakvimlerineislem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musterifirmabilgileriduzen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musterifirmakayitsil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iskontoyapabilsin)
                .addContainerGap(766, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout udspanel58Layout = new javax.swing.GroupLayout(udspanel58);
        udspanel58.setLayout(udspanel58Layout);
        udspanel58Layout.setHorizontalGroup(
            udspanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(udspanel58Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel264)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        udspanel58Layout.setVerticalGroup(
            udspanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(udspanel58Layout.createSequentialGroup()
                .addGroup(udspanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel264)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(udspanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(udspanel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bankahesaphareket;
    private javax.swing.JCheckBox bankahesaptanimla;
    private javax.swing.JCheckBox barkodyaz;
    private javax.swing.JCheckBox dovizkurlari;
    private javax.swing.JCheckBox faturaayar;
    private javax.swing.JCheckBox firmatakvimlerineislem;
    private javax.swing.JCheckBox genelayar;
    private javax.swing.JCheckBox hareketduzenleyebilsin;
    private javax.swing.JCheckBox hareketiptaletme;
    private javax.swing.JCheckBox irsaliyeayar;
    private javax.swing.JCheckBox irsaliyefaturaayar;
    private javax.swing.JCheckBox irsaliyefaturayaz;
    private javax.swing.JCheckBox iskontoyapabilsin;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox musterifirmabilgileriduzen;
    private javax.swing.JCheckBox musterifirmakayitsil;
    private javax.swing.JCheckBox musteritakvimlerineislem;
    private javax.swing.JCheckBox personelodeme;
    private javax.swing.JCheckBox personeltanimla;
    private javax.swing.JCheckBox satisfisiayar;
    private javax.swing.JCheckBox satisfiyatdegistirme;
    private javax.swing.JCheckBox sifredegistir;
    private javax.swing.JCheckBox smsgonder;
    private javax.swing.JPanel udspanel58;
    private javax.swing.JCheckBox yapilacakirsaliyefaturalist;
    // End of variables declaration//GEN-END:variables
}
