/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege;
import GUI_Packege.personel.MaasOde;
import GUI_Packege.database.Database;
import GUI_Packege.personel.*;
import GUI_Packege.okul.*;
import GUI_Packege.ogrenci.*;
import GUI_Packege.kasa.*;
import GUI_Packege.arac.*;
import StudentServiceClass.DbConnection;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author zehirugur
 */
public class Main_Frame extends javax.swing.JFrame {
    OgrenciKayit ok;
    OgrenciHareket oh;
    AracKayit ak;
    AracHareket ah;
    OkulKayit okulk;
    PersonelKayit pk;
    OkulHareket okulH;
    PersonelHareket ph;
    OdemeBilgisiOlustur to;
    OgrenciOdemeEkrani ooe;
    OgrenciTaksitAyrintiEkrani oae;
    Database dbase;
    DbConnection databs;
    KasaGoster kg;
    AracinGidecegiOkullar ago;
    MaasOde mo;
    AracKiraOde aracko;
    AracGiderOde aracgo;
    MaasOdemeEkrani moe;
    OgrenciTaksitOde oto;
    AracaGuzergah ag;
    OgrencilerinAraclaraDagitimi oad;
    AracGiderEkrani aracge;
    AracKiraEkrani aracke;    
    /**
     * Creates new form Main_Frame
     */
    public Main_Frame()
    {
       initComponents();
       databs = new DbConnection();
       aracko = new AracKiraOde(databs);
       aracgo = new AracGiderOde(databs);
       oad=new OgrencilerinAraclaraDagitimi(databs);
       oto = new OgrenciTaksitOde(databs);
       dbase = new Database(databs);
       to = new OdemeBilgisiOlustur(databs);
       ok = new OgrenciKayit(databs);
       oh = new OgrenciHareket(ok,to,databs);
       ak = new AracKayit(databs);
       ah = new AracHareket(ak,databs);
       okulk = new OkulKayit(databs);
       okulH = new OkulHareket(okulk,databs);
       pk = new PersonelKayit(databs);
       mo = new MaasOde(databs);
       ph = new PersonelHareket(pk,databs,mo);
       oae = new OgrenciTaksitAyrintiEkrani(databs,oto);
       ooe = new OgrenciOdemeEkrani(oae,databs);
       kg = new KasaGoster(databs);
       ago = new AracinGidecegiOkullar(databs);
       ag = new AracaGuzergah(databs);
       moe = new MaasOdemeEkrani(databs);
       aracge=new AracGiderEkrani(databs, aracgo);
       aracke = new AracKiraEkrani(databs, aracko);
       
       jDesktopPane1.add(dbase);
       jDesktopPane1.add(oae);
       jDesktopPane1.add(to);
       jDesktopPane1.add(ah);
       jDesktopPane1.add(ph);
       jDesktopPane1.add(okulH);
       jDesktopPane1.add(ok);
       jDesktopPane1.add(oh);
       jDesktopPane1.add(ak);
       jDesktopPane1.add(okulk);
       jDesktopPane1.add(pk);
       jDesktopPane1.add(ooe);
       jDesktopPane1.add(kg);
       jDesktopPane1.add(ago);
       jDesktopPane1.add(moe);
       jDesktopPane1.add(mo);
       jDesktopPane1.add(oto);
       jDesktopPane1.add(ag);
       jDesktopPane1.add(oad);
       jDesktopPane1.add(aracko);
       jDesktopPane1.add(aracge);
       jDesktopPane1.add(aracke);
       jDesktopPane1.add(aracgo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        ogrenci_hareket = new javax.swing.JButton();
        ogrenci_kaydet = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        okul_kaydet = new javax.swing.JButton();
        okul_hareket = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Personel_Kaydet = new javax.swing.JButton();
        Personel_Hareket = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Arac_Kaydet = new javax.swing.JButton();
        Arac_Hareket = new javax.swing.JButton();
        Arac_Okul_Kayit = new javax.swing.JButton();
        Arac_Hareket1 = new javax.swing.JButton();
        Arac_Okul_Kayit1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Arac_Kaydet1 = new javax.swing.JButton();
        odeme_sekli = new javax.swing.JButton();
        Arac_Kaydet2 = new javax.swing.JButton();
        Arac_Kaydet3 = new javax.swing.JButton();
        Arac_Kaydet4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("nanoTech_yazılım");
        setExtendedState(6);

        ogrenci_hareket.setText("<html><center>ÖĞRENCİ<br>HAREKET<center><html>");
        ogrenci_hareket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_hareketActionPerformed(evt);
            }
        });

        ogrenci_kaydet.setText("<html><center>ÖĞRENCİ<br> KAYDET</center></html>");
        ogrenci_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ogrenci_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ogrenci_hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 567, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("   ÖĞRENCİ   ", jPanel3);

        okul_kaydet.setText("<html><center>OKUL<br> KAYDET</center></html>");
        okul_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okul_kaydetActionPerformed(evt);
            }
        });

        okul_hareket.setText("<html><center>OKUL<br> HAREKET</center></html>");
        okul_hareket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okul_hareketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(okul_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okul_hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 579, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okul_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okul_hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("     OKUL      ", jPanel4);

        Personel_Kaydet.setText("<html><center>PERSONEL<br> KAYDET</center></html>");
        Personel_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personel_KaydetActionPerformed(evt);
            }
        });

        Personel_Hareket.setText("<html><center>PERSONEL<br> HAREKET</center></html>");
        Personel_Hareket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personel_HareketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Personel_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Personel_Hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 565, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personel_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Personel_Hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab(" PERSONEL ", jPanel5);

        Arac_Kaydet.setText("<html><center>ARAÇ<br> KAYDET</center></html>");
        Arac_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_KaydetActionPerformed(evt);
            }
        });

        Arac_Hareket.setText("<html><center>ARAÇ<br>HAREKET</center></html>");
        Arac_Hareket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_HareketActionPerformed(evt);
            }
        });

        Arac_Okul_Kayit.setText("<html><center>ARAÇ>OKUL<br>KAYDI</center></html>");
        Arac_Okul_Kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Okul_KayitActionPerformed(evt);
            }
        });

        Arac_Hareket1.setText("<html><center>ARAÇ<br>GÜZERGAHI</center></html>");
        Arac_Hareket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Hareket1ActionPerformed(evt);
            }
        });

        Arac_Okul_Kayit1.setText("<html><center>ARAÇ>ÖĞRENCİ<br>KAYDI</center></html>");
        Arac_Okul_Kayit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Okul_Kayit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Arac_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Okul_Kayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Okul_Kayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Hareket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 264, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arac_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Okul_Kayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Hareket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Okul_Kayit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("     ARAÇ     ", jPanel6);

        Arac_Kaydet1.setText("<html><center>KASA<br>GÖSTER</center></html>");
        Arac_Kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Kaydet1ActionPerformed(evt);
            }
        });

        odeme_sekli.setText("<html><center>TAKSİT ÖDEME<center><html>");
        odeme_sekli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        odeme_sekli.setPreferredSize(new java.awt.Dimension(79, 37));
        odeme_sekli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odeme_sekliActionPerformed(evt);
            }
        });

        Arac_Kaydet2.setText("<html><center>MAAŞ<br>ÖDEME</center></html>");
        Arac_Kaydet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Kaydet2ActionPerformed(evt);
            }
        });

        Arac_Kaydet3.setText("<html><center>ARAÇ<br>GİDERLERİ</center></html>");
        Arac_Kaydet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Kaydet3ActionPerformed(evt);
            }
        });

        Arac_Kaydet4.setText("<html><center>ARAÇ<br>KİRALARI</center></html>");
        Arac_Kaydet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arac_Kaydet4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Arac_Kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Kaydet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arac_Kaydet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odeme_sekli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 320, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Arac_Kaydet1)
                    .addComponent(Arac_Kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Kaydet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arac_Kaydet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odeme_sekli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("     KASA     ", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("Dosya");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenu6.setText("jMenu6");
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu4.setText("jMenu4");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Araçlar");

        jMenuItem1.setText("Database");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void ogrenci_hareketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_hareketActionPerformed
        oh.getKayit();
        oh.okulCagir();
        showJIFrame(oh);
    }//GEN-LAST:event_ogrenci_hareketActionPerformed
    private void ogrenci_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_kaydetActionPerformed
        ok.Okul_Cagir();
        showJIFrame(ok);
    }//GEN-LAST:event_ogrenci_kaydetActionPerformed
    private void okul_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okul_kaydetActionPerformed
    showJIFrame(okulk);
    }//GEN-LAST:event_okul_kaydetActionPerformed
    private void okul_hareketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okul_hareketActionPerformed
        okulH.getKayit();
        showJIFrame(okulH);
    }//GEN-LAST:event_okul_hareketActionPerformed
    private void Personel_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personel_KaydetActionPerformed
        showJIFrame(pk);
    }//GEN-LAST:event_Personel_KaydetActionPerformed
    private void Arac_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_KaydetActionPerformed
        ak.Personel_Cagir();
        showJIFrame(ak);
    }//GEN-LAST:event_Arac_KaydetActionPerformed
    private void Personel_HareketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personel_HareketActionPerformed
        ph.getKayit();
        showJIFrame(ph);
    }//GEN-LAST:event_Personel_HareketActionPerformed
    private void Arac_HareketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_HareketActionPerformed
        showJIFrame(ah);
        ah.getKayit();
    }//GEN-LAST:event_Arac_HareketActionPerformed
    private void odeme_sekliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odeme_sekliActionPerformed
        ooe.getKayit();   
        showJIFrame(ooe);
    }//GEN-LAST:event_odeme_sekliActionPerformed
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        showJIFrame(dbase);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Arac_Kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Kaydet1ActionPerformed
        showJIFrame(kg);
    }//GEN-LAST:event_Arac_Kaydet1ActionPerformed

    private void Arac_Okul_KayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Okul_KayitActionPerformed
        ago.Okul_Cagir();
        ago.Servis_Cagir();
        ago.Gidilen_Okul_Tablo();
        showJIFrame(ago);
    }//GEN-LAST:event_Arac_Okul_KayitActionPerformed

    private void Arac_Kaydet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Kaydet2ActionPerformed
        moe.filTable();        
        showJIFrame(moe);
    }//GEN-LAST:event_Arac_Kaydet2ActionPerformed

    private void Arac_Hareket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Hareket1ActionPerformed
        ag.Guzergah_Okul_Cagir();
        ag.Guzergah_Servis_Cagir();
        ag.Servis_Dagitilan_Ogrenci();
        showJIFrame(ag);
    }//GEN-LAST:event_Arac_Hareket1ActionPerformed

    private void Arac_Okul_Kayit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Okul_Kayit1ActionPerformed
        oad.Okul_CagirG();
        oad.Servis_CagirG();
        oad.studentCountNotAdd();
        showJIFrame(oad);
    }//GEN-LAST:event_Arac_Okul_Kayit1ActionPerformed

    private void Arac_Kaydet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Kaydet3ActionPerformed
      showJIFrame(aracge); 
    }//GEN-LAST:event_Arac_Kaydet3ActionPerformed

    private void Arac_Kaydet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arac_Kaydet4ActionPerformed
        showJIFrame(aracke);
    }//GEN-LAST:event_Arac_Kaydet4ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new logform().setVisible(true);
                new Main_Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arac_Hareket;
    private javax.swing.JButton Arac_Hareket1;
    private javax.swing.JButton Arac_Kaydet;
    private javax.swing.JButton Arac_Kaydet1;
    private javax.swing.JButton Arac_Kaydet2;
    private javax.swing.JButton Arac_Kaydet3;
    private javax.swing.JButton Arac_Kaydet4;
    private javax.swing.JButton Arac_Okul_Kayit;
    private javax.swing.JButton Arac_Okul_Kayit1;
    private javax.swing.JButton Personel_Hareket;
    private javax.swing.JButton Personel_Kaydet;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton odeme_sekli;
    private javax.swing.JButton ogrenci_hareket;
    private javax.swing.JButton ogrenci_kaydet;
    private javax.swing.JButton okul_hareket;
    private javax.swing.JButton okul_kaydet;
    // End of variables declaration//GEN-END:variables
private void showJIFrame(javax.swing.JInternalFrame xxx){
        xxx.show(true);
    try {
        xxx.setSelected(true);
    }catch (PropertyVetoException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "JInternalFrame Error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
    }
}
}
