/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Packege.kasa;

import GUI_Packege.ogrenci.OgrenciHareket;
import StudentServiceClass.DbConnection;
import StudentServiceClass.ReinstalData;
import StudentServiceClass.TableToExcel;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
/**
 *
 *
 * @author zehirugur
 */
public class OgrenciOdemeEkrani extends javax.swing.JInternalFrame {
ReinstalData rid=new ReinstalData();
DbConnection databs;
OgrenciTaksitAyrintiEkrani OgrAyrEkr;
/**
     * Creates new form Ogrenci_Hareket
     * 
     * @param oae
     * @param databs
     */
    public OgrenciOdemeEkrani(OgrenciTaksitAyrintiEkrani oae,DbConnection databs) {
    this.databs=databs;
        initComponents();
        setLocation(getWidth()/2,getHeight()/10);   
       OgrAyrEkr=oae;
       
    }
public void getKayit()
{
    
String firTable = "select distinct\n" +
"    t.OGRENCI_ID,\n" +
"    o.ADI,\n" +
"    o.SOYADI,\n" +
"    o.VELI_ADI,\n" +
"    DATE_FORMAT(t.OLUSTURMA_TARIH,'%d-%m-%Y') OLUŞTURULAN_TARİH,\n" +
"    SUM(t.TAKSIT_MIKTARI) AS TOPLAM,\n" +
"    SUM(t.ODENEN_MIKTAR) AS ÖDENEN\n" +        
"from \n" +
"    taksit t,\n" +
"    ogrenci o\n" +
"WHERE \n" +
"    o.ID=t.OGRENCI_ID AND\n";

    if(iptal_check.isSelected()==true){
    firTable+="  t.IPTAL = 1";
    }
    if(iptal_check.isSelected()==false){
    firTable+="  t.IPTAL = 0";
    }
    if(!ID.getText().equals(""))
    {
    firTable+=" AND t.OGRENCI_ID LIKE "+ID.getText()+"";
    }
    if(!ADI.getText().equals(""))
    {
    firTable+=" AND O.ADI LIKE '"+ADI.getText()+"%'";
    }
    if(!SOYADI.getText().equals(""))
    {
    firTable+=" AND O.SOYADI LIKE '"+SOYADI.getText()+"%'";
    }
    if(!VELI_ADI.getText().equals(""))
    {
    firTable+=" AND O.VELI_ADI LIKE '"+VELI_ADI.getText()+"%'";
    }
   firTable+=" GROUP BY t.OGRENCI_ID ";
    try {  
        databs.openDatabase();
        databs.sttmnt.execute(firTable);
        ResultSet rs = databs.sttmnt.getResultSet();
        ODEME_TABLO.setModel(DbUtils.resultSetToTableModel(rs));
    
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciOdemeEkrani.class.getName()).log(Level.SEVERE, null, ex);
    }finally
    {
    databs.closeDatabase();
    }
}
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ODEME_TABLO = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ID = new javax.swing.JTextField();
        VELI_ADI = new javax.swing.JTextField();
        ADI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SOYADI = new javax.swing.JTextField();
        ARA = new javax.swing.JButton();
        iptal_check = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        Exel_Yaz = new javax.swing.JButton();
        detayGoster = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Öğrenci Ödemeleri");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ODEME_TABLO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    ODEME_TABLO.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            ODEME_TABLOMouseReleased(evt);
        }
    });
    jScrollPane1.setViewportView(ODEME_TABLO);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ara", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

    jLabel5.setText("ID");

    jLabel1.setText("VELİ ADI");

    jLabel2.setText("ADI");

    jLabel4.setText("SOYADI");

    ARA.setText("Ara");
    ARA.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ARAActionPerformed(evt);
        }
    });

    iptal_check.setText("İPTAL");
    iptal_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    iptal_check.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(SOYADI, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addComponent(jLabel1))
                .addComponent(iptal_check))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(ARA, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addComponent(VELI_ADI))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(jLabel2)
                .addComponent(jLabel4)
                .addComponent(SOYADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(VELI_ADI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addGap(3, 3, 3)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ARA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(iptal_check, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Çıktı", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

    Exel_Yaz.setText("Exelle Yaz");
    Exel_Yaz.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Exel_YazActionPerformed(evt);
        }
    });

    detayGoster.setText("Detay Göster");
    detayGoster.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            detayGosterActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(Exel_Yaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(detayGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Exel_Yaz)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(detayGoster)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARAActionPerformed
    getKayit();
    }//GEN-LAST:event_ARAActionPerformed

    private void Exel_YazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exel_YazActionPerformed
        try {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel", "xls", "xlsx");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showDialog(null,"Kaydet");
        if(returnVal == JFileChooser.APPROVE_OPTION) 
        {
         TableToExcel tte = new TableToExcel(ODEME_TABLO, null, "My Table");
//        tte.setCustomTitles(str);
         File myfile = new File(chooser.getSelectedFile().getPath()+".xls");
         tte.generate(myfile);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog( null,ex.getMessage(), "Write to Excel Error. Tablo Yazdırılamadı.", JOptionPane.ERROR_MESSAGE );
        Logger.getLogger(OgrenciHareket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_Exel_YazActionPerformed

    private void detayGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detayGosterActionPerformed
        if(ODEME_TABLO.getSelectedRow()!=-1)
        {
            secilenOgr();
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Lütfen Bir Öğrenci Seçin.");
    }//GEN-LAST:event_detayGosterActionPerformed

    private void ODEME_TABLOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ODEME_TABLOMouseReleased
        if(evt.getClickCount()==2)
            secilenOgr();
    }//GEN-LAST:event_ODEME_TABLOMouseReleased
    private void secilenOgr()
    {
        OgrAyrEkr.ogrenciBilgi((int)ODEME_TABLO.getModel().getValueAt(ODEME_TABLO.getSelectedRow(),0));
        OgrAyrEkr.filTable((int)ODEME_TABLO.getModel().getValueAt(ODEME_TABLO.getSelectedRow(),0));
        OgrAyrEkr.show(true);
    }
    
    private void getSil()
    {
  if(ODEME_TABLO.getSelectedRow()!=-1){
     int result = JOptionPane.showOptionDialog(null, 
     (String)ODEME_TABLO.getModel().getValueAt(ODEME_TABLO.getSelectedRow(),1)+" "+(String)ODEME_TABLO.getModel().getValueAt(ODEME_TABLO.getSelectedRow(),2)+" S�L�NECEK! S�LMEK istedi�inize eminmisiniz.", 
     "Feedback", 
     JOptionPane.OK_CANCEL_OPTION, 
     JOptionPane.WARNING_MESSAGE, 
     null, 
     new String[]{"EVET", "HAYIR"},
        "default");
     if(result==JOptionPane.OK_OPTION)
     {
databs.openDatabase();   
String sqlAccess="UPDATE ogrenci SET IPTAL=1 WHERE ID="+ODEME_TABLO.getModel().getValueAt(ODEME_TABLO.getSelectedRow(),0)+"";
try
{
databs.sttmnt.executeUpdate(sqlAccess);
}catch(SQLException e)
{
    JOptionPane.showMessageDialog( null,e.getMessage(), "Database error", JOptionPane.ERROR_MESSAGE );
Logger.getLogger(OgrenciOdemeEkrani.class.getName()).log(Level.SEVERE, null, e);
}finally{
databs.closeDatabase();}
     }
  }else{
  JOptionPane.showMessageDialog(rootPane," Lütfen silmek istediğniz kişiyi seçiniz.");
  }
  getKayit();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADI;
    private javax.swing.JButton ARA;
    private javax.swing.JButton Exel_Yaz;
    private javax.swing.JTextField ID;
    private javax.swing.JTable ODEME_TABLO;
    private javax.swing.JTextField SOYADI;
    private javax.swing.JTextField VELI_ADI;
    private javax.swing.JButton detayGoster;
    private javax.swing.JCheckBox iptal_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
